feat: Integrate frontend with backend

diff --git a/frontend/Makefile b/frontend/Makefile
--- a/frontend/Makefile
+++ b/frontend/Makefile
@@ -1,8 +1,25 @@
+SHELL=/bin/bash
+
 deploy: infra_deploy code_deploy
 destroy: infra_destroy
 
+BACKEND_SERVICE_URL=$(shell cd ../backend && $(MAKE) -s api_url | head -n 2)
+	
+serve:
+	@if [[ "$(BACKEND_SERVICE_URL)" == *"No outputs found"* ]] ; then \
+		echo "Backend service URL not found, please go to the backend service and deploy it first."; \
+		exit 1; \
+	fi
+	export VITE_BACKEND_SERVICE_URL=$(BACKEND_SERVICE_URL) && \
+		yarn run dev
+
 code_build:
-	yarn run build
+	@if [[ "$(BACKEND_SERVICE_URL)" == *"No outputs found"* ]] ; then \
+		echo "Backend service URL not found, please go to the backend service and deploy it first."; \
+		exit 1; \
+	fi
+	export VITE_BACKEND_SERVICE_URL=$(BACKEND_SERVICE_URL) && \
+		yarn run build
 
 code_deploy: code_build
 	. ./source.sh && \
